// -----------------------------------------------------------------------
// <copyright file="CSharpGenerator.cs" company="Cricle">
// Copyright (c) Cricle. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Sqlx;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;

/// <summary>
/// Stored procedures generator for C#.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class CSharpGenerator : AbstractGenerator
{
    private const string CSharpAttributeSource = @"// <auto-generated>
// Code generated by Sqlx Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable

using System.Data;
using System.Data.Common;
using System.Diagnostics;

namespace Sqlx.Annotations
{
    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    sealed class SqlxAttribute : global::System.Attribute
    {
        public SqlxAttribute()
            => StoredProcedureName = string.Empty;

        public SqlxAttribute(string name)
            => StoredProcedureName = name;

        public string StoredProcedureName { get; }

        public string ParameterPrefix { get; set; } = ""@"";
    }

    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
    sealed class RawSqlAttribute : global::System.Attribute { }

    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false)]
    sealed class ExecuteNoQueryAttribute : global::System.Attribute { }

    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method
        | global::System.AttributeTargets.Class
        | global::System.AttributeTargets.Field
        | global::System.AttributeTargets.Property
        | global::System.AttributeTargets.Method
        | global::System.AttributeTargets.Parameter, AllowMultiple = false)]
    sealed class TimeoutAttribute : global::System.Attribute
    {
        public TimeoutAttribute() { }

        public TimeoutAttribute(int timeout) => Timeout = timeout;

        public int Timeout { get; }
    }

    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
    sealed class DbColumnAttribute : global::System.Attribute
    {
        public DbColumnAttribute() { }

        public DbColumnAttribute(string? name) => Name = name;

        public string? Name { get; }

        public byte Precision { get; }
        public byte Scale { get; }
        public byte Size { get; }
        public global::System.Data.ParameterDirection Direction { get; }
    }

    /// <summary>
    /// Tag to paramter make it as <see cref=""Func{DbDataReader, Task}""/> or <see cref=""Action{DbDataReader}""/> for read data
    /// </summary>
    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
    sealed class ReaderHandlerAttribute : global::System.Attribute { }

    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false)]
    sealed class DbSetTypeAttribute : global::System.Attribute
    {
        public DbSetTypeAttribute(global::System.Type type) => Type = type;


        public global::System.Type Type { get; }
    }

    [global::System.Diagnostics.Conditional(""DEBUG"")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Method | global::System.AttributeTargets.Class, AllowMultiple = false)]
    sealed class SqlDefineAttribute : global::System.Attribute
    {
        public SqlDefineAttribute(SqlDefineTypes type) { }

        public SqlDefineAttribute(global::System.String ColumnLeft,
                                  global::System.String ColumnRight,
                                  global::System.String StringLeft,
                                  global::System.String StringRight,
                                  global::System.String ParamterPrefx) { }
    }

    enum SqlDefineTypes
    {
        MySql = 0,
        SqlServer = 1,
        Postgresql = 2,

    }
}
";

    /// <inheritdoc/>
    public override void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForPostInitialization((pi) =>
        {
            pi.AddSource("SqlxAttribute.g.cs", CSharpAttributeSource);
        });
        context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
    }

    internal class SyntaxReceiver : ISqlxSyntaxReceiver
    {
        public List<IMethodSymbol> Methods { get; } = new List<IMethodSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            // any field with at least one attribute is a candidate for property generation
            if (context.Node is MethodDeclarationSyntax methodDeclarationSyntax)
            {
                // Get the symbol being declared by the field, and keep it if its annotated
                if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not IMethodSymbol methodSymbol) return;

                if (methodSymbol.GetAttributes().Any(ad => ad.AttributeClass?.ToDisplayString() == "Sqlx.Annotations.SqlxAttribute"))
                {
                    Methods.Add(methodSymbol);
                }
            }
        }
    }
}
