// -----------------------------------------------------------------------
// <copyright file="CSharpGenerator.cs" company="Cricle">
// Copyright (c) Cricle. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Sqlx;

using Microsoft.CodeAnalysis;
using Sqlx;
using System.Diagnostics;

/// <summary>
/// Stored procedures generator for C#.
/// </summary>
//[Generator(LanguageNames.CSharp)]
public partial class CSharpGenerator : AbstractGenerator
{
    // Attributes are now provided by Sqlx project - no need to generate them

    /// <summary>
    /// Initializes a new instance of the <see cref="CSharpGenerator"/> class.
    /// </summary>
    public CSharpGenerator()
    {
        // Initialize performance monitoring for source generation
#if DEBUG
        Debug.WriteLine("🚀 Sqlx CSharpGenerator initialized with advanced optimizations");
#endif
    }

    // Syntax receiver moved to partial file: CSharpGenerator.SyntaxReceiver.cs

    /// <summary>
    /// Called to initialize the generator and register for the various 
    /// <see cref="SyntaxNode"/>
    /// callbacks.
    /// </summary>
    /// <param name="context">The generator context.</param>
    public override void Initialize(GeneratorInitializationContext context)
    {
#if DEBUG
        System.Diagnostics.Debug.WriteLine("CSharpGenerator.Initialize called");
        System.Console.WriteLine("🚀 CSharpGenerator.Initialize called");
#endif
        context.RegisterForSyntaxNotifications(() => new CSharpSyntaxReceiver());
        
        // Add a simple test source to verify the generator is working
        context.RegisterForPostInitialization(ctx =>
        {
#if DEBUG
            System.Console.WriteLine("🧪 PostInitialization called - adding test source");
#endif
            var testSource = @"// Generated by Sqlx Source Generator - Test
namespace Sqlx.Generated
{
    public static class GeneratorTest
    {
        public static string GetMessage() => ""Sqlx Source Generator is working!"";
    }
}";
            ctx.AddSource("GeneratorTest.g.cs", testSource);
        });
    }
}

