// -----------------------------------------------------------------------
// <auto-generated>
// -----------------------------------------------------------------------

namespace Sqlx;

using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

public partial class CSharpGenerator
{
    /// <summary>
    /// C# specific syntax receiver for collecting method symbols and repository classes.
    /// </summary>
    private class CSharpSyntaxReceiver : ISqlxSyntaxReceiver, ISyntaxReceiver
    {
        public List<IMethodSymbol> Methods { get; } = new List<IMethodSymbol>();
        public List<INamedTypeSymbol> RepositoryClasses { get; } = new List<INamedTypeSymbol>();
        
        // Collect syntax nodes for later processing
        public List<MethodDeclarationSyntax> MethodSyntaxNodes { get; } = new List<MethodDeclarationSyntax>();
        public List<ClassDeclarationSyntax> ClassSyntaxNodes { get; } = new List<ClassDeclarationSyntax>();

        public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
        {
            // Collect method declarations with potential Sqlx attributes
            if (syntaxNode is MethodDeclarationSyntax methodDeclaration && HasSqlxAttributeSyntax(methodDeclaration))
            {
                MethodSyntaxNodes.Add(methodDeclaration);
            }
            // Collect class declarations with potential RepositoryFor attributes
            else if (syntaxNode is ClassDeclarationSyntax classDeclaration && HasRepositoryForAttributeSyntax(classDeclaration))
            {
                ClassSyntaxNodes.Add(classDeclaration);
            }
        }

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            var semanticModel = context.SemanticModel;
            
            // Collect methods with Sqlx attributes
            if (context.Node is MethodDeclarationSyntax methodDeclaration && 
                semanticModel.GetDeclaredSymbol(methodDeclaration) is IMethodSymbol method && 
                HasSqlxAttribute(method))
            {
                Methods.Add(method);
            }
            // Collect repository classes with RepositoryFor attributes
            else if (context.Node is ClassDeclarationSyntax classDeclaration && 
                     semanticModel.GetDeclaredSymbol(classDeclaration) is INamedTypeSymbol type && 
                     HasRepositoryForAttribute(type))
            {
                RepositoryClasses.Add(type);
            }
        }

        private static bool HasSqlxAttribute(IMethodSymbol method)
        {
            // Only collect methods declared in classes to avoid generating implementations for interfaces
            if (method.ContainingType == null || method.ContainingType.TypeKind != TypeKind.Class)
            {
                return false;
            }

            // Prefer semantic attribute check when available
            if (method.GetAttributes().Any(attr =>
                attr.AttributeClass?.Name == "SqlxAttribute" ||
                attr.AttributeClass?.Name == "Sqlx" ||
                // RawSqlAttribute merged into SqlxAttribute
                attr.AttributeClass?.Name == "SqlExecuteTypeAttribute" ||
                attr.AttributeClass?.Name == "SqlExecuteType"))
            {
                return true;
            }

            // Fallback: syntax-based detection so tests without using directives still work
            var syntax = method.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() as Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax;
            if (syntax != null)
            {
                foreach (var attrList in syntax.AttributeLists)
                {
                    foreach (var attr in attrList.Attributes)
                    {
                        var nameText = attr.Name.ToString();
                        if (nameText is "Sqlx" or "SqlxAttribute" or "SqlExecuteType" or "SqlExecuteTypeAttribute")
                        {
                            return true;
                        }
                    }
                }
            }

            return false;
        }

        private static bool HasSqlxAttributeSyntax(MethodDeclarationSyntax methodDeclaration) =>
            methodDeclaration.AttributeLists.Any(attrList =>
                attrList.Attributes.Any(attr =>
                    attr.Name.ToString() is "Sqlx" or "SqlxAttribute" or "SqlExecuteType" or "SqlExecuteTypeAttribute"));

        private static bool HasRepositoryForAttributeSyntax(ClassDeclarationSyntax classDeclaration) =>
            classDeclaration.AttributeLists.Any(attrList =>
                attrList.Attributes.Any(attr =>
                    attr.Name.ToString() is "RepositoryFor" or "RepositoryForAttribute"));

        private static bool HasRepositoryForAttribute(INamedTypeSymbol type) =>
            type.GetAttributes().Any(attr => 
                attr.AttributeClass?.Name is "RepositoryForAttribute" or "RepositoryFor");
    }
}


