// <copyright file="ParameterBinderGenerator.cs" company="Sqlx">
// Copyright (c) Sqlx. All rights reserved.
// </copyright>

namespace Sqlx;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

/// <summary>
/// Generates IParameterBinder implementations for [SqlxParameter] classes.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class ParameterBinderGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetTarget(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(classes.Collect()),
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static ClassDeclarationSyntax? GetTarget(GeneratorSyntaxContext ctx)
    {
        var c = (ClassDeclarationSyntax)ctx.Node;
        foreach (var al in c.AttributeLists)
            foreach (var a in al.Attributes)
                if (a.Name.ToString() is "SqlxParameter" or "SqlxParameterAttribute")
                    return c;
        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax?> classes, SourceProductionContext ctx)
    {
        if (classes.IsDefaultOrEmpty) return;

        var sqlxAttr = compilation.GetTypeByMetadataName("Sqlx.Annotations.SqlxParameterAttribute");
        if (sqlxAttr is null) return;

        var ignoreAttr = compilation.GetTypeByMetadataName("System.Runtime.Serialization.IgnoreDataMemberAttribute");
        var columnAttr = compilation.GetTypeByMetadataName("System.ComponentModel.DataAnnotations.Schema.ColumnAttribute");
        var processedTypes = new System.Collections.Generic.HashSet<string>();
        var parameterTypes = new System.Collections.Generic.List<INamedTypeSymbol>();

        foreach (var c in classes.Distinct())
        {
            if (c is null) continue;
            var model = compilation.GetSemanticModel(c.SyntaxTree);
            if (model.GetDeclaredSymbol(c) is not INamedTypeSymbol hostTypeSymbol) continue;

            var attrs = hostTypeSymbol.GetAttributes()
                .Where(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, sqlxAttr))
                .ToList();
            if (attrs.Count == 0) continue;

            foreach (var attr in attrs)
            {
                // Check for TargetType in constructor argument
                INamedTypeSymbol targetType;
                if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is INamedTypeSymbol targetTypeArg)
                {
                    targetType = targetTypeArg;
                }
                else
                {
                    targetType = hostTypeSymbol;
                }

                var typeKey = targetType.ToDisplayString();
                if (processedTypes.Contains(typeKey)) continue;
                processedTypes.Add(typeKey);

                parameterTypes.Add(targetType);
                ctx.AddSource($"{targetType.Name}.ParameterBinder.g.cs", SourceText.From(Generate(targetType, ignoreAttr, columnAttr), Encoding.UTF8));
            }
        }

        // Generate ModuleInitializer for all parameter binder types
        if (parameterTypes.Count > 0)
        {
            var moduleInitSource = GenerateModuleInitializer(parameterTypes);
            ctx.AddSource("ParameterBinders.ModuleInit.g.cs", SourceText.From(moduleInitSource, Encoding.UTF8));
        }
    }

    private static string Generate(INamedTypeSymbol ts, INamedTypeSymbol? ignoreAttr, INamedTypeSymbol? columnAttr)
    {
        var ns = ts.ContainingNamespace.IsGlobalNamespace ? "Global" : ts.ContainingNamespace.ToDisplayString();
        var name = ts.Name;
        var full = ts.ToDisplayString();

        var props = ts.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod is not null)
            .Where(p => ignoreAttr is null || !p.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, ignoreAttr)))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine("using System; using System.Data; using System.Data.Common;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {name}ParameterBinder : global::Sqlx.IParameterBinder<{full}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {name}ParameterBinder Default {{ get; }} = new();");
        sb.AppendLine();

        // DbCommand binding
        sb.AppendLine($"    public void BindEntity(DbCommand cmd, {full} e, string prefix = \"@\")");
        sb.AppendLine("    {");
        foreach (var p in props)
        {
            var col = GetColumnName(p, columnAttr);
            var val = IsNullable(p) || p.Type.IsReferenceType ? $"e.{p.Name} ?? (object)DBNull.Value" : $"e.{p.Name}";
            sb.AppendLine($"        {{ var p = cmd.CreateParameter(); p.ParameterName = prefix + \"{col}\"; p.Value = {val}; cmd.Parameters.Add(p); }}");
        }
        sb.AppendLine("    }");

        // DbBatchCommand binding (.NET 6+)
        sb.AppendLine("#if NET6_0_OR_GREATER");
        sb.AppendLine($"    public void BindEntity(DbBatchCommand cmd, {full} e, Func<DbParameter> f, string prefix = \"@\")");
        sb.AppendLine("    {");
        foreach (var p in props)
        {
            var col = GetColumnName(p, columnAttr);
            var val = IsNullable(p) || p.Type.IsReferenceType ? $"e.{p.Name} ?? (object)DBNull.Value" : $"e.{p.Name}";
            sb.AppendLine($"        {{ var p = f(); p.ParameterName = prefix + \"{col}\"; p.Value = {val}; cmd.Parameters.Add(p); }}");
        }
        sb.AppendLine("    }");
        sb.AppendLine("#endif");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetColumnName(IPropertySymbol p, INamedTypeSymbol? columnAttr)
    {
        if (columnAttr is not null)
        {
            var a = p.GetAttributes().FirstOrDefault(x => SymbolEqualityComparer.Default.Equals(x.AttributeClass, columnAttr));
            if (a?.ConstructorArguments.Length > 0 && a.ConstructorArguments[0].Value is string n) return n;
        }
        return ToSnakeCase(p.Name);
    }

    private static string ToSnakeCase(string s)
    {
        var sb = new StringBuilder(s.Length + 4);
        for (int i = 0; i < s.Length; i++)
        {
            var c = s[i];
            if (char.IsUpper(c) && i > 0) sb.Append('_');
            sb.Append(char.ToLowerInvariant(c));
        }
        return sb.ToString();
    }

    private static bool IsNullable(IPropertySymbol p) =>
        p.NullableAnnotation == NullableAnnotation.Annotated ||
        (p.Type.IsValueType && p.Type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T);

    private static string GenerateModuleInitializer(System.Collections.Generic.List<INamedTypeSymbol> parameterTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Sqlx.Generated;");
        sb.AppendLine();
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("internal static class ParameterBindersInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Register all parameter binders");

        foreach (var type in parameterTypes)
        {
            var fullTypeName = type.ToDisplayString();
            var typeName = type.Name;
            var ns = type.ContainingNamespace.IsGlobalNamespace ? "Global" : type.ContainingNamespace.ToDisplayString();
            sb.AppendLine($"        global::Sqlx.SqlQuery<{fullTypeName}>.ParameterBinder = global::{ns}.{typeName}ParameterBinder.Default;");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
