using Microsoft.Data.Sqlite;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Sqlx;
using Sqlx.Annotations;
using System;
using System.Linq;
using System.Threading.Tasks;

#if NET10_0_OR_GREATER
// .NET 10+ has built-in async LINQ support
#else
using System.Linq.Async;
#endif

namespace Sqlx.Tests;

[Sqlx]
public class TestUser
{
    public long Id { get; set; }
    public string Name { get; set; } = "";
    public int Age { get; set; }
}

public interface ITestUserRepository : ICrudRepository<TestUser, long>
{
    // AsQueryable() 应该由 ICrudRepository 接口提供
    // 源生成器应该自动生成实现
}

[SqlDefine(SqlDefineTypes.SQLite)]
[TableName("TestUser")]
[RepositoryFor(typeof(ITestUserRepository))]
public partial class TestUserRepository(SqliteConnection connection) : ITestUserRepository
{
    // 不应该手动实现 AsQueryable()
    // 源生成器会自动生成
}

[TestClass]
public class AsQueryableGenerationTests
{
    [TestMethod]
    public void AsQueryable_ShouldBeAutoGenerated()
    {
        // Arrange
        using var connection = new SqliteConnection("Data Source=:memory:");
        connection.Open();
        var repo = new TestUserRepository(connection);

        // Act
        var queryable = repo.AsQueryable();

        // Assert
        Assert.IsNotNull(queryable);
        Assert.IsInstanceOfType(queryable, typeof(IQueryable<TestUser>));
    }

    [TestMethod]
    public async Task AsQueryable_ShouldWorkWithLinqQueries()
    {
        // Arrange
        using var connection = new SqliteConnection("Data Source=:memory:");
        connection.Open();
        
        using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = @"
                CREATE TABLE TestUser (
                    id INTEGER PRIMARY KEY,
                    name TEXT NOT NULL,
                    age INTEGER NOT NULL
                )";
            await cmd.ExecuteNonQueryAsync();
        }

        using (var cmd = connection.CreateCommand())
        {
            cmd.CommandText = @"
                INSERT INTO TestUser (name, age) VALUES 
                ('Alice', 25),
                ('Bob', 30),
                ('Charlie', 35)";
            await cmd.ExecuteNonQueryAsync();
        }

        var repo = new TestUserRepository(connection);

        // Act
        var query = repo.AsQueryable()
            .Where(u => u.Age >= 30)
            .OrderBy(u => u.Name);
        
        // Cast to IAsyncEnumerable to use async LINQ
        var asyncQuery = (System.Collections.Generic.IAsyncEnumerable<TestUser>)query;
        var users = await System.Linq.AsyncEnumerable.ToListAsync<TestUser>(asyncQuery, default);

        // Assert
        Assert.AreEqual(2, users.Count);
        Assert.AreEqual("Bob", users[0].Name);
        Assert.AreEqual("Charlie", users[1].Name);
    }
}
