// -----------------------------------------------------------------------
// <copyright file="TestRepository.cs" company="Cricle">
// Copyright (c) Cricle. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace Sqlx.BasicExample;

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Threading;
using Sqlx.Annotations;

/// <summary>
/// Test entity for demonstration
/// </summary>
[TableName("test_users")]
public class TestUser
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
}

/// <summary>
/// Test service interface
/// </summary>
public interface ITestUserService
{
    IList<TestUser> GetAllUsers();
    
    Task<IList<TestUser>> GetAllUsersAsync(CancellationToken cancellationToken = default);
    
    TestUser? GetUserById(int id);
    
    Task<TestUser?> GetUserByIdAsync(int id, CancellationToken cancellationToken = default);
    
    int CreateUser(TestUser user);
    
    Task<int> CreateUserAsync(TestUser user, CancellationToken cancellationToken = default);
    
    int UpdateUser(TestUser user);
    
    int DeleteUser(int id);
}

/// <summary>
/// Repository implementation that will be automatically generated by Sqlx
/// This class should only have the RepositoryFor attribute - no manual implementation
/// </summary>
[RepositoryFor(typeof(ITestUserService))]
public partial class TestUserRepository : ITestUserService
{
    private readonly System.Data.Common.DbConnection connection;

    public TestUserRepository(System.Data.Common.DbConnection connection)
    {
        this.connection = connection ?? throw new ArgumentNullException(nameof(connection));
    }
    
    // 所有方法由 RepositoryFor 源生成器自动实现
}
