// -----------------------------------------------------------------------
// <copyright file="MethodGenerationBatchCommandTests.cs" company="Cricle">
// Copyright (c) Cricle. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;

namespace Sqlx.Tests.Core
{
    [TestClass]
    public class MethodGenerationBatchCommandTests
    {
        [TestMethod]
        public void BatchCommand_Without_CollectionParam_Emits_UserFriendly_Error()
        {
            var source = @"using Sqlx.Annotations; using System.Data.Common; using System.Threading.Tasks; 
namespace N { 
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.BatchCommand, ""users"")] Task<int> ExecAsync();
  }
}";

            var code = string.Join("\n", Generate(source));
            StringAssert.Contains(code, "BatchCommand requires a collection parameter");
        }

        [TestMethod]
        public void BatchCommand_With_CollectionParam_Generates_NullCheck_And_NativeDbBatch_Path()
        {
            var source = @"using Sqlx.Annotations; using System.Data.Common; using System.Threading.Tasks; using System.Collections.Generic; 
namespace N { 
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.BatchCommand, ""users"")] Task<int> ExecAsync(IList<int> ids);
  }
}";

            var code = string.Join("\n", Generate(source));
            StringAssert.Contains(code, "if (ids == null)");
            // Native DbBatch path indicators
            StringAssert.Contains(code, "CanCreateBatch");
            StringAssert.Contains(code, "CreateBatch()");
            StringAssert.Contains(code, "BatchCommands.Add");
        }

        private static List<string> Generate(string source)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(source);
            var references = new List<MetadataReference>
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.Data.Common.DbConnection).Assembly.Location)
            };

            var compilation = CSharpCompilation.Create(
                "BatchCmdAsm",
                new[] { syntaxTree },
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var generator = new CSharpGenerator();
            var driver = CSharpGeneratorDriver.Create(generator);
            driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out var diags);

            var generated = new List<string>();
            foreach (var tree in newCompilation.SyntaxTrees)
            {
                var text = tree.ToString();
                if (text.Contains("// <auto-generated>") || string.IsNullOrEmpty(tree.FilePath))
                    generated.Add(text);
            }
            return generated;
        }
    }
}


