// -----------------------------------------------------------------------
// <copyright file="MethodGenerationNonQueryAndScalarTests.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;

namespace Sqlx.Tests.Core;

[TestClass]
public class MethodGenerationNonQueryAndScalarTests
{
    [TestMethod]
    public void Generated_NonQuery_Returns_Bool_Without_Convert()
    {
        var source = @"using System.Data.Common; using Sqlx.Annotations; using System.Threading.Tasks;
namespace TestNS {
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.Update, ""users"")] Task<bool> UpdateNameAsync();
  }
}";

        var code = Generate(source);
        Assert.IsFalse(code.Contains("Convert.ToInt32"));
        Assert.IsTrue(code.Contains("> 0") || code.Contains("ExecuteNonQueryAsync"));
    }

    [TestMethod]
    public void Generated_Scalar_String_Direct_Return_No_ChangeType()
    {
        var source = @"using System.Data.Common; using Sqlx.Annotations; using System.Threading.Tasks;
namespace TestNS {
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [RawSql(""SELECT name FROM users WHERE id=1"")] Task<string> GetNameAsync();
  }
}";

        var code = Generate(source);
        Assert.IsFalse(code.Contains("ChangeType"));
        Assert.IsTrue(
            code.Contains("ExecuteScalar(") ||
            code.Contains("ExecuteScalarAsync") ||
            code.Contains("SELECT name FROM users WHERE id=1")
        );
    }

    [TestMethod]
    public void Generated_Scalar_Decimal_Direct_Return_No_ChangeType()
    {
        var source = @"using System.Data.Common; using Sqlx.Annotations; using System.Threading.Tasks;
namespace TestNS {
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [RawSql(""SELECT price FROM products WHERE id=1"")] Task<decimal> GetPriceAsync();
  }
}";

        var code = Generate(source);
        Assert.IsFalse(code.Contains("ChangeType"));
        Assert.IsTrue(
            code.Contains("ExecuteScalar(") ||
            code.Contains("ExecuteScalarAsync") ||
            code.Contains("SELECT price FROM products WHERE id=1")
        );
    }

    private static string Generate(string source)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);
        var references = new List<MetadataReference>
        {
            MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Data.Common.DbConnection).Assembly.Location),
            MetadataReference.CreateFromFile(typeof(System.Threading.Tasks.Task).Assembly.Location)
        };

        var compilation = CSharpCompilation.Create(
            "GenAsmNonQuery",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new CSharpGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out var diagnostics);

        var generated = new List<string>();
        foreach (var tree in newCompilation.SyntaxTrees)
        {
            var text = tree.ToString();
            if (text.Contains("// <auto-generated>") || string.IsNullOrEmpty(tree.FilePath))
            {
                generated.Add(text);
            }
        }
        return string.Join("\n", generated);
    }
}


