// -----------------------------------------------------------------------
// <copyright file="SourceGeneratorBatchPathsTests.cs" company="Cricle">
// Copyright (c) Cricle. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Sqlx.Tests.Core
{
    [TestClass]
    public class SourceGeneratorBatchPathsTests
    {
        [TestMethod]
        public void Generated_BatchInsert_UsesBatchCommandAndAddsParameters()
        {
            var source = @"using System.Data.Common; using Sqlx.Annotations; 
namespace TestNS { 
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.BatchInsert, ""users"")] int BatchCreate(System.Collections.Generic.IList<User> users);
  }
  [TableName(""users"")] public class User { public int Id {get;set;} public string Name {get;set;} = string.Empty; }
}";

            var generated = Generate(source);
            var code = string.Join("\n", generated);

            Assert.IsTrue(code.Contains("CreateBatchCommand"), "Should create batch command");
            Assert.IsTrue(code.Contains("BatchCommands.Add"), "Should add to BatchCommands");
            Assert.IsTrue(code.Contains("Parameters.Add"), "Should add parameters to batchCommand");
        }

        [TestMethod]
        public void Generated_BatchUpdate_ContainsUpdateSetAndWhere()
        {
            var source = @"using System.Data.Common; using Sqlx.Annotations; 
namespace TestNS { 
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.BatchUpdate, ""users"")] int BatchUpdate(System.Collections.Generic.IList<User> users);
  }
  [TableName(""users"")] public class User { public int Id {get;set;} public string Name {get;set;} = string.Empty; }
}";

            var generated = Generate(source);
            var code = string.Join("\n", generated);

            Assert.IsTrue(code.Contains("UPDATE"), "Should generate UPDATE");
            Assert.IsTrue(code.Contains("SET"), "Should include SET clause");
            Assert.IsTrue(code.Contains("WHERE Id"), "Should include WHERE by Id");
        }

        [TestMethod]
        public void Generated_BatchDelete_ContainsDeleteWhere()
        {
            var source = @"using System.Data.Common; using Sqlx.Annotations; 
namespace TestNS { 
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.BatchDelete, ""users"")] int BatchDelete(System.Collections.Generic.IList<int> ids);
  }
}";

            var generated = Generate(source);
            var code = string.Join("\n", generated);

            Assert.IsTrue(code.Contains("DELETE FROM"), "Should generate DELETE");
            Assert.IsTrue(code.Contains("WHERE"), "Should include WHERE clause");
        }

        private static List<string> Generate(string source)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(source);
            var references = new List<MetadataReference>
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.Data.Common.DbConnection).Assembly.Location)
            };

            var compilation = CSharpCompilation.Create(
                "GenAsm",
                new[] { syntaxTree },
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var generator = new CSharpGenerator();
            var driver = CSharpGeneratorDriver.Create(generator);
            driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out var diagnostics);

            var generated = new List<string>();
            foreach (var tree in newCompilation.SyntaxTrees)
            {
                var text = tree.ToString();
                if (text.Contains("// <auto-generated>") || string.IsNullOrEmpty(tree.FilePath))
                {
                    generated.Add(text);
                }
            }
            return generated;
        }
    }
}


