// -----------------------------------------------------------------------
// <copyright file="SourceGeneratorDeleteSafetyTests.cs" company="Cricle">
// Copyright (c) Cricle. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.Linq;

namespace Sqlx.Tests.Core
{
    [TestClass]
    public class SourceGeneratorDeleteSafetyTests
    {
        [TestMethod]
        public void Delete_ById_And_ByEntity_ShouldContainWhere()
        {
            var source = @"using System.Data.Common; using Sqlx.Annotations; using System.Threading.Tasks; 
namespace N {
  [TableName(""users"")] public class User { public int Id {get;set;} public string Name {get;set;} = string.Empty; }
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.Delete, ""users"")] Task<int> DeleteByIdAsync(int id);
    [SqlExecuteType(SqlExecuteTypes.Delete, ""users"")] Task<int> DeleteByEntityAsync(User entity);
  }
}";

            var generated = Generate(source);
            var code = string.Join("\n", generated);
            Assert.IsTrue(code.Contains("DELETE FROM"));
            Assert.IsTrue(code.Contains("WHERE"), "DELETE safety: WHERE clause should be present");
        }

        [TestMethod]
        public void BatchDelete_ByIds_ShouldContainWhere()
        {
            var source = @"using System.Collections.Generic; using System.Data.Common; using Sqlx.Annotations; using System.Threading.Tasks; 
namespace N {
  [RepositoryFor(typeof(IRepo))]
  public partial class Repo : IRepo { private readonly DbConnection connection; public Repo(DbConnection c){connection=c;} }
  public interface IRepo {
    [SqlExecuteType(SqlExecuteTypes.BatchDelete, ""users"")] Task<int> DeleteManyAsync(IList<int> ids);
  }
}";

            var generated = Generate(source);
            var code = string.Join("\n", generated);
            Assert.IsTrue(code.Contains("DELETE FROM"));
            Assert.IsTrue(code.Contains("WHERE"), "Batch DELETE safety: WHERE clause should be present");
        }

        private static List<string> Generate(string source)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(source);
            var references = new List<MetadataReference>
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.Data.Common.DbConnection).Assembly.Location)
            };

            var compilation = CSharpCompilation.Create(
                "DelSafetyAsm",
                new[] { syntaxTree },
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var generator = new CSharpGenerator();
            var driver = CSharpGeneratorDriver.Create(generator);
            driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out var diags);

            var generated = new List<string>();
            foreach (var tree in newCompilation.SyntaxTrees)
            {
                var text = tree.ToString();
                if (text.Contains("// <auto-generated>") || string.IsNullOrEmpty(tree.FilePath))
                    generated.Add(text);
            }
            return generated;
        }
    }
}


