// -----------------------------------------------------------------------
// <copyright file="ISchemaRepositoryTests.cs" company="Cricle">
// Copyright (c) Cricle. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Sqlx;
using Sqlx.Annotations;

namespace Sqlx.Tests.Predefined
{
    /// <summary>
    /// Tests for ISchemaRepository predefined interface.
    /// Validates that all methods are correctly defined and can be generated by the source generator.
    /// Requirements: 11.4, 15.4 - Ensure ISchemaRepository methods generate correct implementation code.
    /// </summary>
    [TestClass]
    public class ISchemaRepositoryTests : IDisposable
    {
        private readonly SqliteConnection _connection;

        public ISchemaRepositoryTests()
        {
            _connection = new SqliteConnection("Data Source=:memory:");
            _connection.Open();
        }

        public void Dispose()
        {
            _connection?.Dispose();
        }

        #region Interface Method Coverage Tests

        /// <summary>
        /// Verifies all ISchemaRepository methods are defined.
        /// </summary>
        [TestMethod]
        public void ISchemaRepository_AllMethodsShouldBeDefined()
        {
            var interfaceType = typeof(ISchemaRepository<>);
            var methods = interfaceType.GetMethods();
            var methodNames = methods.Select(m => m.Name).ToList();

            // Schema Operations
            CollectionAssert.Contains(methodNames, "TableExistsAsync");
            CollectionAssert.Contains(methodNames, "GenerateCreateTableSqlAsync");
            CollectionAssert.Contains(methodNames, "CreateTableIfNotExistsAsync");
            CollectionAssert.Contains(methodNames, "GetColumnNamesAsync");
            CollectionAssert.Contains(methodNames, "GetApproximateRowCountAsync");
            CollectionAssert.Contains(methodNames, "GetTableSizeBytesAsync");
        }

        /// <summary>
        /// Verifies ISchemaRepository method signatures are correct.
        /// </summary>
        [TestMethod]
        public void ISchemaRepository_MethodSignatures_ShouldBeCorrect()
        {
            var interfaceType = typeof(ISchemaRepository<>);
            var methods = interfaceType.GetMethods();

            // TableExistsAsync should return Task<bool>
            var tableExistsMethod = methods.FirstOrDefault(m => m.Name == "TableExistsAsync");
            Assert.IsNotNull(tableExistsMethod, "TableExistsAsync should exist");
            Assert.AreEqual(typeof(Task<bool>), tableExistsMethod.ReturnType, "TableExistsAsync should return Task<bool>");
            Assert.AreEqual(1, tableExistsMethod.GetParameters().Length, "TableExistsAsync should have 1 parameter (CancellationToken)");
            Assert.AreEqual(typeof(CancellationToken), tableExistsMethod.GetParameters()[0].ParameterType);

            // GenerateCreateTableSqlAsync should return Task<string>
            var generateDdlMethod = methods.FirstOrDefault(m => m.Name == "GenerateCreateTableSqlAsync");
            Assert.IsNotNull(generateDdlMethod, "GenerateCreateTableSqlAsync should exist");
            Assert.AreEqual(typeof(Task<string>), generateDdlMethod.ReturnType, "GenerateCreateTableSqlAsync should return Task<string>");

            // CreateTableIfNotExistsAsync should return Task (void async)
            var createTableMethod = methods.FirstOrDefault(m => m.Name == "CreateTableIfNotExistsAsync");
            Assert.IsNotNull(createTableMethod, "CreateTableIfNotExistsAsync should exist");
            Assert.AreEqual(typeof(Task), createTableMethod.ReturnType, "CreateTableIfNotExistsAsync should return Task");

            // GetColumnNamesAsync should return Task<IList<string>>
            var getColumnsMethod = methods.FirstOrDefault(m => m.Name == "GetColumnNamesAsync");
            Assert.IsNotNull(getColumnsMethod, "GetColumnNamesAsync should exist");
            Assert.AreEqual(typeof(Task<IList<string>>), getColumnsMethod.ReturnType, "GetColumnNamesAsync should return Task<IList<string>>");

            // GetApproximateRowCountAsync should return Task<long>
            var getRowCountMethod = methods.FirstOrDefault(m => m.Name == "GetApproximateRowCountAsync");
            Assert.IsNotNull(getRowCountMethod, "GetApproximateRowCountAsync should exist");
            Assert.AreEqual(typeof(Task<long>), getRowCountMethod.ReturnType, "GetApproximateRowCountAsync should return Task<long>");

            // GetTableSizeBytesAsync should return Task<long>
            var getTableSizeMethod = methods.FirstOrDefault(m => m.Name == "GetTableSizeBytesAsync");
            Assert.IsNotNull(getTableSizeMethod, "GetTableSizeBytesAsync should exist");
            Assert.AreEqual(typeof(Task<long>), getTableSizeMethod.ReturnType, "GetTableSizeBytesAsync should return Task<long>");
        }

        /// <summary>
        /// Verifies ISchemaRepository has no object parameters (AOT compatible).
        /// </summary>
        [TestMethod]
        public void ISchemaRepository_ShouldNotHaveObjectParameters_AOTCompatible()
        {
            var interfaceType = typeof(ISchemaRepository<>);
            var methods = interfaceType.GetMethods();

            foreach (var method in methods)
            {
                var parameters = method.GetParameters();
                foreach (var param in parameters)
                {
                    Assert.AreNotEqual(typeof(object), param.ParameterType,
                        $"Method {method.Name} has 'object' parameter which is not AOT compatible");
                }
            }
        }

        /// <summary>
        /// Verifies ISchemaRepository has correct generic constraint (TEntity : class).
        /// </summary>
        [TestMethod]
        public void ISchemaRepository_GenericConstraint_ShouldBeClass()
        {
            var interfaceType = typeof(ISchemaRepository<>);
            var typeParam = interfaceType.GetGenericArguments()[0];
            
            var hasClassConstraint = (typeParam.GenericParameterAttributes & 
                GenericParameterAttributes.ReferenceTypeConstraint) != 0;
            Assert.IsTrue(hasClassConstraint, "TEntity should have 'class' constraint");
        }

        /// <summary>
        /// Verifies ISchemaRepository async methods have CancellationToken parameter where appropriate.
        /// Note: GenerateCreateTableSqlAsync doesn't have CancellationToken as it's a pure computation.
        /// </summary>
        [TestMethod]
        public void ISchemaRepository_DatabaseAsyncMethods_ShouldHaveCancellationToken()
        {
            var interfaceType = typeof(ISchemaRepository<>);
            var methods = interfaceType.GetMethods()
                .Where(m => m.Name.EndsWith("Async") && m.Name != "GenerateCreateTableSqlAsync")
                .ToList();

            foreach (var method in methods)
            {
                var parameters = method.GetParameters();
                var hasCancellationToken = parameters.Any(p => p.ParameterType == typeof(CancellationToken));
                Assert.IsTrue(hasCancellationToken, 
                    $"Method {method.Name} should have CancellationToken parameter");
            }
        }

        #endregion

        #region Source Generator Tests

        /// <summary>
        /// Tests that the source generator generates TableExistsAsync correctly.
        /// </summary>
        [TestMethod]
        public async Task SourceGenerated_TableExistsAsync_WhenTableNotExists_ReturnsFalse()
        {
            // Arrange
            var repo = new SchemaTestRepository(_connection);

            // Act
            var exists = await repo.TableExistsAsync();

            // Assert
            Assert.IsFalse(exists);
        }

        /// <summary>
        /// Tests that the source generator generates TableExistsAsync correctly when table exists.
        /// </summary>
        [TestMethod]
        public async Task SourceGenerated_TableExistsAsync_WhenTableExists_ReturnsTrue()
        {
            // Arrange
            await CreateSchemaTestTableAsync();
            var repo = new SchemaTestRepository(_connection);

            // Act
            var exists = await repo.TableExistsAsync();

            // Assert
            Assert.IsTrue(exists);
        }

        /// <summary>
        /// Tests that the source generator generates GetColumnNamesAsync correctly.
        /// </summary>
        [TestMethod]
        public async Task SourceGenerated_GetColumnNamesAsync_ReturnsColumnNames()
        {
            // Arrange
            await CreateSchemaTestTableAsync();
            var repo = new SchemaTestRepository(_connection);

            // Act
            var columns = await repo.GetColumnNamesAsync();

            // Assert
            Assert.IsNotNull(columns);
            Assert.IsTrue(columns.Count > 0);
            // Column names should include id and name
            Assert.IsTrue(columns.Any(c => c.Equals("id", StringComparison.OrdinalIgnoreCase)));
            Assert.IsTrue(columns.Any(c => c.Equals("name", StringComparison.OrdinalIgnoreCase)));
        }

        /// <summary>
        /// Tests that the source generator generates GetApproximateRowCountAsync correctly.
        /// </summary>
        [TestMethod]
        public async Task SourceGenerated_GetApproximateRowCountAsync_ReturnsCount()
        {
            // Arrange
            await CreateSchemaTestTableAsync();
            await InsertTestDataAsync(5);
            var repo = new SchemaTestRepository(_connection);

            // Act
            var count = await repo.GetApproximateRowCountAsync();

            // Assert
            Assert.AreEqual(5L, count);
        }

        #endregion

        #region Helper Methods

        private async Task CreateSchemaTestTableAsync()
        {
            using var cmd = _connection.CreateCommand();
            cmd.CommandText = @"
                CREATE TABLE IF NOT EXISTS schema_test_entities (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    description TEXT,
                    created_at TEXT NOT NULL
                )";
            await cmd.ExecuteNonQueryAsync();
        }

        private async Task InsertTestDataAsync(int count)
        {
            for (int i = 1; i <= count; i++)
            {
                using var cmd = _connection.CreateCommand();
                cmd.CommandText = $@"
                    INSERT INTO schema_test_entities (name, description, created_at)
                    VALUES ('Entity{i}', 'Description {i}', '{DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}')";
                await cmd.ExecuteNonQueryAsync();
            }
        }

        #endregion
    }

    #region Test Entity

    /// <summary>
    /// Test entity for schema repository tests.
    /// </summary>
    [TableName("schema_test_entities")]
    public class SchemaTestEntity
    {
        public long Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string? Description { get; set; }
        public DateTime CreatedAt { get; set; }
    }

    #endregion

    #region Source-Generated Schema Repository Interface

    /// <summary>
    /// Custom interface for schema operations that the source generator can implement.
    /// Uses SqlTemplate attributes to define the SQL for each method.
    /// </summary>
    public interface ISchemaTestRepository
    {
        /// <summary>Checks if table exists using SQLite sqlite_master.</summary>
        [SqlTemplate("SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='schema_test_entities'")]
        Task<bool> TableExistsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>Gets column names using SQLite PRAGMA.</summary>
        [SqlTemplate("SELECT name FROM pragma_table_info('schema_test_entities')")]
        Task<List<string>> GetColumnNamesAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>Gets approximate row count (SQLite uses COUNT(*)).</summary>
        [SqlTemplate("SELECT COUNT(*) FROM schema_test_entities")]
        Task<long> GetApproximateRowCountAsync(System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// Source-generated repository for schema operations.
    /// The source generator will implement the interface methods.
    /// </summary>
    [SqlDefine(SqlDefineTypes.SQLite)]
    [RepositoryFor(typeof(ISchemaTestRepository))]
    public partial class SchemaTestRepository : ISchemaTestRepository
    {
        private readonly IDbConnection _connection;

        public SchemaTestRepository(IDbConnection connection)
        {
            _connection = connection;
        }
    }

    #endregion
}
